export const RoutesTypes = {
  welcome: '/',
  login: '/login',
  registration: '/registration',
  confirmAccount: '/confirmAccount/:accountConfirmToken',
  financials: '/financials',
  bestFinancials: '/bestfinancials',
  financial: '/financials/:id',
  myFinancials: '/myfinancials',
  myFinancial: '/myfinancials/:id',
  credits: '/credits',
  bestCredits: '/bestcredits',
  credit: '/credits/:id',
  myCredits: '/mycredits',
  myCredit: '/mycredits/:id',
  applyForCredit: '/applyForCredit/:id',
  wallet: '/wallet',
  walletPayIn: '/wallet/payin',
  walletWithdraw: '/wallet/withdraw',
  currency: '/currency',
  profile: '/profile',
  profileUpdate: '/profile/update',
  mailbox: '/mailbox',
  mailboxMessage: '/mailbox/:id',
  resetPassword: '/resetPassword',
  setNewPassword: '/setNewPassword/:token',
}