export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

export const GET_FINANCIALS = 'GET_FINANCIALS';
export const GET_FINANCIALS_ERROR = 'GET_FINANCIALS_ERROR';
export const GET_FINANCIAL = 'GET_FINANCIAL';
export const GET_FINANCIAL_ERROR = 'GET_FINANCIAL_ERROR';
export const UPDATED_FINANCIALS_STATUS = 'UPDATED_FINANCIALS_STATUS';
export const CLEAR_UPDATED_FINANCIALS_STATUS = 'CLEAR_UPDATED_FINANCIALS_STATUS';

export const GET_CREDITS = 'GET_CREDITS';
export const GET_CREDITS_ERROR = 'GET_CREDIT_ERRORS';
export const GET_CREDIT = 'GET_CREDIT';
export const GET_CREDIT_ERROR = 'GET_CREDIT_ERROR';
export const RESPONSE_CREDIT_MAIL = 'RESPONSE_CREDIT_MAIL';
export const CLEAR_RESPONSE_CREDIT_MAIL = 'CLEAR_RESPONSE_CREDIT_MAIL';